[project]
name = "atheneum-forge"
version = "0.1.0"
description = "Project boilerplate and build system scaffolding generation and maintenance."
authors = [{ name = "Big Ladder Software", email = "info@bigladdersoftware.com" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = [
    "jinja2>=3.1.4,<4",
    "typer>=0.12.5,<0.13",
    "tomli-w>=1.1.0,<2",
]

[project.scripts]
forge = "atheneum_forge.main:app"

[dependency-groups]
dev = [
    "ruff>=0.7.0,<0.8",
    "pytest>=8.3.3,<9",
    "python-lsp-server>=1.12.0,<2",
    "black>=24.10.0,<25",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["data/python/project", "data/python"]
