[tool.poetry]
name = "boilerplate"
version = "0.1.0"
description = "Project boilerplate and build system scaffolding generation and maintenance."
authors = ["Big Ladder Software <info@bigladdersoftware.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
