static = [
  {from="cmake/build-options-interface.cmake", to="cmake/."},
  {from="cmake/get-git-hash.cmake", to="cmake/."},
  {from="cmake/git-versioning.cmake", to="cmake/."},
  {from="cmake/initialize-submodules.cmake", to="cmake/."},
  {from="cmake/toolchain-windows.cmake", to="cmake/."},
  {from="cmake/Findcodecov.cmake", to="cmake/."},
  {from="cmake/FindGcov.cmake", to="cmake/."},
  {from="cmake/FindLcov.cmake", to="cmake/."},
  {from="cmake/llvm-cov-wrapper.cmake", to="cmake/."},
  {from=".clang-format", to="."},
  {from=".gitignore", to=".", onetime=true},
  {from=".github/*", to=".github/."},
  {from=".github/workflows/build-and-test.yml", to=".github/workflows/."},
  {from=".github/workflows/clang-tidy-check.yml", to=".github/workflows/."},
  {from=".github/workflows/doxygen-completeness-check.yml", to=".github/workflows/."},
  {from="", to="include", onetime=true},
  {from="", to="doc", onetime=true},
  {from="CMakePresets.json", to="."}
]
template = [
  {from="main_CMakeLists.txt.j2", to=".", oname="CMakeLists.txt", add_copyright=true},
  {from="LICENSE.txt", to=".", onetime=true, oname="LICENSE.txt", add_copyright=true},
  {from="README.md.j2", to=".", onetime=true, oname="README.md", add_copyright=true},
  {from="src/src_CMakeLists.txt.j2", to="src/.", oname="CMakeLists.txt", add_copyright=true},
  {from="vendor/vendor_CMakeLists.txt.j2", to="vendor/.", oname="CMakeLists.txt", add_copyright=true},
  {from="test/test_CMakeLists.txt.j2", to="test/.", oname="CMakeLists.txt", add_copyright=true},
  {from="Dockerfile.format.j2", to=".", oname="Dockerfile.format"},
  {from="app/app_CMakeLists.txt.j2", to="app/.", oname="CMakeLists.txt", if="use_app", add_copyright=true},
  {from=".github/workflows/clang-format-check.yml.j2", to=".github/workflows/.", oname="clang-format-check.yml"},
  {from="Taskfile.yml.j2", to=".", onetime=true, oname="Taskfile.yml", if="use_taskfile"},
  {from=".clang-tidy.j2", to=".", oname=".clang-tidy"},
]
[template-parameters]
clang_format_version = {type="int", default=16}
cpp_std = {type="enum", options=["17", "20"], default="20"}
files_app = {type="str:glob", default="app/[a-zA-Z]*.cpp", private=true}
files_app_config = {type="str:glob", default="app/[a-zA-Z]*.*.in", private=true}
files_src = {type="str:glob", default="src/[a-zA-Z]*.cpp", private=true}
files_src_config = {type="str:glob", default="app/[a-zA-Z]*.*.in", private=true}
files_test = {type="str:glob", default="test/[a-zA-Z]*.cpp", private=true}
headers_config = {type="str:glob", default="include/**/[a-zA-Z]*.*.in", private=true}
headers_private = {type="str:glob", default="src/[a-zA-Z]*.h", private=true}
headers_public = {type="str:glob", default="include/**/[a-zA-Z]*.h", private=true}
project_type = {type="str", default="cpp", required=true}
project_short_description = {type="str", default=""}
start_year = {type="int:year", default="current_year()"}
name_of_copyright_holder = {type="str", default = "Big Ladder Software"}
contact_email = {type="str", default = "info@bigladdersoftware.com"}
SPDX_license_name = {type="str", default = "BSD-3-Clause"}
use_app = {type="bool", default=false}
# if use_cmake_version is true, the version in the top-level CMakeLists.txt file
# is the "single source of truth" and the boilerplate project assists in "bumping"
# versions and the like. If set to false, the git history and tag system is used
# as the single-source of truth for versioning. If use_cmake_version is set to false,
# version_major, version_minor, and version_patch won't do anything.
use_cmake_version = {type="bool", default=false}
use_taskfile = {type="bool", default=false}
version_major = {type="int:>=0", default=0}
version_minor = {type="int:>=0", default=1}
version_patch = {type="int:>=0", default=0}
[[deps]]
name = "fmt"
git_url = "https://github.com/fmtlib/fmt.git"
git_checkout = "master"
add_to_cmake = false # already explicitly added
[[deps]]
name = "googletest"
git_url = "https://github.com/google/googletest.git"
git_checkout = "main"
add_to_cmake = false # already explicitly added
link_library_spec = "GTest::gtest_main"
[task.copyright]
copy = """
Copyright (c) {% if start_year is defined and start_year != year %}{{ start_year }} - {% endif %}{{ year }} Big Ladder Software, LLC.
See the LICENSE.txt file for additional terms and conditions."""
[update-strategies]
toml = "dict"
json = "dict"
yaml = "dict"
yml = "dict"
txt = "text"
csv = "text"
md = "text"
cmake = "text"
format = "text"
"" = "text"
